# Generated by Django 5.2.1 on 2025-06-15 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCaoCongNo',
            fields=[
                ('MaBCCN', models.AutoField(primary_key=True, serialize=False)),
                ('Thang', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaoCaoTon',
            fields=[
                ('MaBCTon', models.AutoField(primary_key=True, serialize=False)),
                ('Thang', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DauSach',
            fields=[
                ('MaDauSach', models.AutoField(primary_key=True, serialize=False)),
                ('TenSach', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKhachHang', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=200)),
                ('DiaChi', models.CharField(max_length=200)),
                ('DienThoai', models.CharField(max_length=200, unique=True)),
                ('Email', models.EmailField(max_length=200)),
                ('SoTienNo', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NXB',
            fields=[
                ('MaNXB', models.AutoField(primary_key=True, serialize=False)),
                ('TenNXB', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TacGia',
            fields=[
                ('MaTG', models.AutoField(primary_key=True, serialize=False)),
                ('TenTG', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThamSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLNhapTT', models.PositiveIntegerField()),
                ('TonTD', models.PositiveIntegerField()),
                ('NoTD', models.DecimalField(decimal_places=0, max_digits=15)),
                ('TonTT', models.PositiveIntegerField()),
                ('TiLe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SDQD4', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('MaTheLoai', models.AutoField(primary_key=True, serialize=False)),
                ('TenTheLoai', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('MaHD', models.AutoField(primary_key=True, serialize=False)),
                ('NgayLap', models.DateField()),
                ('TongTien', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15, null=True)),
                ('SoTienTra', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True)),
                ('ConLai', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15, null=True)),
                ('NguoiLapHD', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='HoaDon', to=settings.AUTH_USER_MODEL, verbose_name='Người lập Hóa Đơn')),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='hoadon', to='api.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='CT_HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLBan', models.PositiveIntegerField()),
                ('GiaBan', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15, null=True)),
                ('ThanhTien', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15, null=True)),
                ('MaHD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_hoadon', to='api.hoadon')),
            ],
        ),
        migrations.CreateModel(
            name='CT_BCCongNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoDau', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15, null=True)),
                ('PhatSinh', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15, null=True)),
                ('NoCuoi', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15, null=True)),
                ('MaBCCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baocaocongno')),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.khachhang')),
            ],
        ),
        migrations.AddField(
            model_name='baocaocongno',
            name='MaKH',
            field=models.ManyToManyField(related_name='BaoCaoCongNo', through='api.CT_BCCongNo', to='api.khachhang'),
        ),
        migrations.CreateModel(
            name='PhieuNhapSach',
            fields=[
                ('MaPhieuNhap', models.AutoField(primary_key=True, serialize=False)),
                ('NgayNhap', models.DateField()),
                ('NguoiNhap', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='PhieuNhapSach', to=settings.AUTH_USER_MODEL, verbose_name='Người nhập')),
            ],
        ),
        migrations.CreateModel(
            name='CT_NhapSach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLNhap', models.PositiveIntegerField()),
                ('GiaNhap', models.DecimalField(decimal_places=0, max_digits=15)),
                ('MaPhieuNhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_nhap', to='api.phieunhapsach')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuThuTien',
            fields=[
                ('MaPhieuThu', models.AutoField(primary_key=True, serialize=False)),
                ('NgayThu', models.DateField()),
                ('SoTienThu', models.DecimalField(decimal_places=0, max_digits=15)),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.khachhang')),
                ('NguoiThu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='PhieuThuTien', to=settings.AUTH_USER_MODEL, verbose_name='Người thu')),
            ],
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('MaSach', models.AutoField(primary_key=True, serialize=False)),
                ('NamXB', models.IntegerField()),
                ('SLTon', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('MaDauSach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sach', to='api.dausach')),
                ('NXB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sach', to='api.nxb')),
            ],
        ),
        migrations.AddField(
            model_name='phieunhapsach',
            name='MaSach',
            field=models.ManyToManyField(related_name='PhieuNhapSach', through='api.CT_NhapSach', to='api.sach'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='MaSach',
            field=models.ManyToManyField(related_name='HoaDon', through='api.CT_HoaDon', to='api.sach'),
        ),
        migrations.AddField(
            model_name='ct_nhapsach',
            name='MaSach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sach'),
        ),
        migrations.AddField(
            model_name='ct_hoadon',
            name='MaSach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sach'),
        ),
        migrations.CreateModel(
            name='CT_BCTon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TonDau', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('PhatSinh', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('TonCuoi', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('MaBCTon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baocaoton')),
                ('MaSach', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sach')),
            ],
        ),
        migrations.AddField(
            model_name='baocaoton',
            name='MaSach',
            field=models.ManyToManyField(related_name='BaoCaoTon', through='api.CT_BCTon', to='api.sach'),
        ),
        migrations.AddField(
            model_name='dausach',
            name='MaTG',
            field=models.ManyToManyField(related_name='DauSach', to='api.tacgia'),
        ),
        migrations.AddField(
            model_name='dausach',
            name='MaTheLoai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DauSach', to='api.theloai'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gioiTinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='Nam', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ct_bccongno',
            constraint=models.UniqueConstraint(fields=('MaBCCN', 'MaKH'), name='unique_ct_bao_cao_congno'),
        ),
        migrations.AddConstraint(
            model_name='sach',
            constraint=models.UniqueConstraint(fields=('MaDauSach', 'NXB', 'NamXB'), name='unique_sach'),
        ),
        migrations.AddConstraint(
            model_name='ct_nhapsach',
            constraint=models.UniqueConstraint(fields=('MaPhieuNhap', 'MaSach'), name='unique_ct_nhap_sach'),
        ),
        migrations.AddConstraint(
            model_name='ct_hoadon',
            constraint=models.UniqueConstraint(fields=('MaHD', 'MaSach'), name='unique_ct_hoa_don'),
        ),
        migrations.AddConstraint(
            model_name='ct_bcton',
            constraint=models.UniqueConstraint(fields=('MaBCTon', 'MaSach'), name='unique_ct_bao_cao_ton'),
        ),
    ]
