# Generated by Django 5.2 on 2025-05-08 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCaoCongNo',
            fields=[
                ('MaBCCN', models.AutoField(primary_key=True, serialize=False)),
                ('Thang', models.IntegerField()),
                ('Nam', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BaoCaoTon',
            fields=[
                ('MaBCTon', models.AutoField(primary_key=True, serialize=False)),
                ('Thang', models.IntegerField()),
                ('Nam', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DauSach',
            fields=[
                ('MaDauSach', models.AutoField(primary_key=True, serialize=False)),
                ('TenSach', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKhachHang', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=200)),
                ('DiaChi', models.CharField(max_length=200)),
                ('DienThoai', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('SoTienNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TacGia',
            fields=[
                ('MaTG', models.AutoField(primary_key=True, serialize=False)),
                ('TenTG', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ThamSo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SLNhapTT', models.IntegerField()),
                ('TonTD', models.IntegerField()),
                ('NoTD', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TonTT', models.IntegerField()),
                ('TiLe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SDQD4', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('MaTheLoai', models.AutoField(primary_key=True, serialize=False)),
                ('TenTheLoai', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('MaHD', models.AutoField(primary_key=True, serialize=False)),
                ('NgayLap', models.DateField()),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SoTienTra', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ConLai', models.DecimalField(decimal_places=2, max_digits=15)),
                ('NguoiLapHD', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NguoiLapHD', to=settings.AUTH_USER_MODEL, verbose_name='Người lập Hóa Đơn')),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='CT_HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLBan', models.IntegerField()),
                ('GiaBan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ThanhTien', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('MaHD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hoadon')),
            ],
        ),
        migrations.CreateModel(
            name='CT_BCCongNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoDau', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PhatSinh', models.DecimalField(decimal_places=2, max_digits=15)),
                ('NoCuoi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MaBCCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baocaocongno')),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.khachhang')),
            ],
            options={
                'unique_together': {('MaBCCN', 'MaKH')},
            },
        ),
        migrations.AddField(
            model_name='baocaocongno',
            name='MaKH',
            field=models.ManyToManyField(related_name='BaoCaoCongNo', through='api.CT_BCCongNo', to='api.khachhang'),
        ),
        migrations.CreateModel(
            name='PhieuNhapSach',
            fields=[
                ('MaPhieuNhap', models.AutoField(primary_key=True, serialize=False)),
                ('NgayNhap', models.DateField()),
                ('NguoiNhap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NguoiNhap', to=settings.AUTH_USER_MODEL, verbose_name='Người nhập')),
            ],
        ),
        migrations.CreateModel(
            name='CT_NhapSach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLNhap', models.IntegerField()),
                ('GiaNhap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MaPhieuNhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phieunhapsach')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuThuTien',
            fields=[
                ('MaPhieuThu', models.AutoField(primary_key=True, serialize=False)),
                ('NgayThu', models.DateField()),
                ('SoTienThu', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.khachhang')),
                ('NguoiThu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='NguoiThu', to=settings.AUTH_USER_MODEL, verbose_name='Người thu')),
            ],
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('MaSach', models.AutoField(primary_key=True, serialize=False)),
                ('NXB', models.CharField(max_length=200)),
                ('NamXB', models.IntegerField()),
                ('SLTon', models.IntegerField()),
                ('MaDauSach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sach', to='api.dausach')),
            ],
        ),
        migrations.AddField(
            model_name='phieunhapsach',
            name='MaSach',
            field=models.ManyToManyField(related_name='PhieuNhapSach', through='api.CT_NhapSach', to='api.sach'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='MaSach',
            field=models.ManyToManyField(related_name='HoaDon', through='api.CT_HoaDon', to='api.sach'),
        ),
        migrations.AddField(
            model_name='ct_nhapsach',
            name='MaSach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sach'),
        ),
        migrations.AddField(
            model_name='ct_hoadon',
            name='MaSach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sach'),
        ),
        migrations.CreateModel(
            name='CT_BCTon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TonDau', models.IntegerField()),
                ('PhatSinh', models.IntegerField()),
                ('TonCuoi', models.IntegerField(editable=False)),
                ('MaBCTon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baocaoton')),
                ('MaSach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sach')),
            ],
            options={
                'unique_together': {('MaBCTon', 'MaSach')},
            },
        ),
        migrations.AddField(
            model_name='baocaoton',
            name='MaSach',
            field=models.ManyToManyField(related_name='BaoCaoTon', through='api.CT_BCTon', to='api.sach'),
        ),
        migrations.AddField(
            model_name='dausach',
            name='MaTG',
            field=models.ManyToManyField(blank=True, related_name='DauSach', to='api.tacgia'),
        ),
        migrations.AddField(
            model_name='dausach',
            name='MaTheLoai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DauSach', to='api.theloai'),
        ),
        migrations.CreateModel(
            name='GroupModelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_change', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'unique_together': {('group', 'model_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ct_nhapsach',
            unique_together={('MaPhieuNhap', 'MaSach')},
        ),
        migrations.AlterUniqueTogether(
            name='ct_hoadon',
            unique_together={('MaHD', 'MaSach')},
        ),
    ]
