# Generated by Django 5.2 on 2025-05-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ct_nhapsach",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="dausach",
            name="TenSach",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="tacgia",
            name="TenTG",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="theloai",
            name="TenTheLoai",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name="ct_nhapsach",
            constraint=models.UniqueConstraint(
                fields=("MaPhieuNhap", "MaSach"), name="unique_ct_nhap_sach"
            ),
        ),
        migrations.AddConstraint(
            model_name="sach",
            constraint=models.UniqueConstraint(
                fields=("MaDauSach", "NXB", "NamXB"), name="unique_sach"
            ),
        ),
    ]
