# Generated by Django 5.2.1 on 2025-06-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='SoTienTra',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=15, null=True),
        ),
    ]
