# Generated by Django 5.2 on 2025-05-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='MaKH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoadon', to='api.khachhang'),
        ),
    ]
