# Generated by Django 5.2 on 2025-05-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupModelPermission',
        ),
    ]
