# Generated by Django 5.2 on 2025-05-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_ct_nhapsach_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ct_nhapsach",
            name="GiaNhap",
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
