# Generated by Django 5.2 on 2025-05-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_ct_nhapsach_gianhap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thamso",
            name="NoTD",
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="thamso",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
