# Generated by Django 5.2 on 2025-05-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_thamso_notd_alter_thamso_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ct_hoadon",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="ct_nhapsach",
            name="SLNhap",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="phieuthutien",
            name="SoTienThu",
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AddConstraint(
            model_name="ct_hoadon",
            constraint=models.UniqueConstraint(
                fields=("MaHD", "MaSach"), name="unique_ct_hoa_don"
            ),
        ),
    ]
