# Generated by Django 5.2 on 2025-05-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_ct_hoadon_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ct_hoadon",
            name="GiaBan",
            field=models.DecimalField(
                decimal_places=0, default=0, editable=False, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ct_hoadon",
            name="ThanhTien",
            field=models.DecimalField(
                decimal_places=0, default=0, editable=False, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hoadon",
            name="ConLai",
            field=models.DecimalField(
                decimal_places=0, default=0, editable=False, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hoadon",
            name="SoTienTra",
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="hoadon",
            name="TongTien",
            field=models.DecimalField(
                decimal_places=0, default=0, editable=False, max_digits=15, null=True
            ),
        ),
    ]
