# Generated by Django 5.2 on 2025-05-28 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_ct_hoadon_giaban_alter_ct_hoadon_thanhtien_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ct_hoadon",
            name="MaHD",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ct_hoadon",
                to="api.hoadon",
            ),
        ),
        migrations.AlterField(
            model_name="ct_hoadon",
            name="SLBan",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="ct_nhapsach",
            name="MaPhieuNhap",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ct_nhap",
                to="api.phieunhapsach",
            ),
        ),
    ]
