# Generated by Django 5.2 on 2025-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_ct_hoadon_mahd_alter_ct_hoadon_slban_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hoadon",
            name="SoTienTra",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=15, null=True
            ),
        ),
    ]
