# Generated by Django 5.2 on 2025-05-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_hoadon_sotientra"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ct_bccongno",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="ct_bcton",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="baocaocongno",
            name="Nam",
        ),
        migrations.RemoveField(
            model_name="baocaoton",
            name="Nam",
        ),
        migrations.AlterField(
            model_name="baocaocongno",
            name="Thang",
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name="baocaoton",
            name="Thang",
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name="ct_bccongno",
            name="NoCuoi",
            field=models.DecimalField(
                decimal_places=0, default=0, editable=False, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ct_bccongno",
            name="NoDau",
            field=models.DecimalField(
                decimal_places=0, default=0, editable=False, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ct_bccongno",
            name="PhatSinh",
            field=models.DecimalField(
                decimal_places=0, default=0, editable=False, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ct_bcton",
            name="PhatSinh",
            field=models.PositiveIntegerField(
                blank=True, default=0, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ct_bcton",
            name="TonCuoi",
            field=models.PositiveIntegerField(
                blank=True, default=0, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ct_bcton",
            name="TonDau",
            field=models.PositiveIntegerField(
                blank=True, default=0, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="khachhang",
            name="SoTienNo",
            field=models.DecimalField(
                decimal_places=0, default=0, editable=False, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sach",
            name="SLTon",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="thamso",
            name="SLNhapTT",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="thamso",
            name="TonTD",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="thamso",
            name="TonTT",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="ct_bccongno",
            constraint=models.UniqueConstraint(
                fields=("MaBCCN", "MaKH"), name="unique_ct_bao_cao_congno"
            ),
        ),
        migrations.AddConstraint(
            model_name="ct_bcton",
            constraint=models.UniqueConstraint(
                fields=("MaBCTon", "MaSach"), name="unique_ct_bao_cao_ton"
            ),
        ),
    ]
