# Generated by Django 5.2 on 2025-05-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ct_bccongno_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupModelPermission',
        ),
    ]
