# Generated by Django 5.2.1 on 2025-06-01 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_groupmodelpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NXB',
            fields=[
                ('MaNXB', models.AutoField(primary_key=True, serialize=False)),
                ('TenNXB', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sach',
            name='NXB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nxb', to='api.nxb'),
        ),
    ]
