# Generated by Django 5.2 on 2025-04-28 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCaoCongNo',
            fields=[
                ('MaBCCN', models.AutoField(primary_key=True, serialize=False)),
                ('Thang', models.IntegerField()),
                ('Nam', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BaoCaoTon',
            fields=[
                ('MaBCTon', models.AutoField(primary_key=True, serialize=False)),
                ('Thang', models.IntegerField()),
                ('Nam', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DauSach',
            fields=[
                ('MaDauSach', models.AutoField(primary_key=True, serialize=False)),
                ('TenSach', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKH', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=100)),
                ('DiaChi', models.CharField(blank=True, max_length=200, null=True)),
                ('DienThoai', models.CharField(blank=True, max_length=15, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('SoTienNo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhapSach',
            fields=[
                ('MaPhieuNhap', models.AutoField(primary_key=True, serialize=False)),
                ('NgayNhap', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TacGia',
            fields=[
                ('MaTG', models.AutoField(primary_key=True, serialize=False)),
                ('TenTG', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ThamSo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SLNhapTT', models.IntegerField()),
                ('TonTD', models.IntegerField()),
                ('NoTD', models.DecimalField(decimal_places=2, max_digits=15)),
                ('TonTT', models.IntegerField()),
                ('TiLe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SDQD4', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('MaTheLoai', models.AutoField(primary_key=True, serialize=False)),
                ('TenTheLoai', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('MaHD', models.AutoField(primary_key=True, serialize=False)),
                ('NgayLap', models.DateField()),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SoTienTra', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ConLai', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuThuTien',
            fields=[
                ('MaPhieuThu', models.AutoField(primary_key=True, serialize=False)),
                ('NgayThu', models.DateField()),
                ('SoTienThu', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('MaSach', models.AutoField(primary_key=True, serialize=False)),
                ('NXB', models.CharField(max_length=100)),
                ('NamXB', models.IntegerField()),
                ('SLTon', models.IntegerField()),
                ('MaDauSach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.dausach')),
            ],
        ),
        migrations.AddField(
            model_name='dausach',
            name='MaTheLoai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.theloai'),
        ),
        migrations.CreateModel(
            name='CT_BCCongNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoDau', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PhatSinh', models.DecimalField(decimal_places=2, max_digits=15)),
                ('NoCuoi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MaBCCN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.baocaocongno')),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.khachhang')),
            ],
            options={
                'unique_together': {('MaBCCN', 'MaKH')},
            },
        ),
        migrations.CreateModel(
            name='CT_NhapSach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLNhap', models.IntegerField()),
                ('GiaNhap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MaPhieuNhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.phieunhapsach')),
                ('MaSach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.sach')),
            ],
            options={
                'unique_together': {('MaPhieuNhap', 'MaSach')},
            },
        ),
        migrations.CreateModel(
            name='CT_HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLBan', models.IntegerField()),
                ('GiaBan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ThanhTien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MaHD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.hoadon')),
                ('MaSach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.sach')),
            ],
            options={
                'unique_together': {('MaHD', 'MaSach')},
            },
        ),
        migrations.CreateModel(
            name='CT_BCTon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TonDau', models.IntegerField()),
                ('PhatSinh', models.IntegerField()),
                ('TonCuoi', models.IntegerField()),
                ('MaBCTon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.baocaoton')),
                ('MaSach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.sach')),
            ],
            options={
                'unique_together': {('MaBCTon', 'MaSach')},
            },
        ),
        migrations.CreateModel(
            name='DauSach_TacGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaDauSach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.dausach')),
                ('MaTG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.tacgia')),
            ],
            options={
                'unique_together': {('MaDauSach', 'MaTG')},
            },
        ),
    ]
