# Generated by Django 5.2 on 2025-05-07 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='NguoiLapHD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hoadon_created', to=settings.AUTH_USER_MODEL, verbose_name='Người lập HĐ'),
        ),
        migrations.AddField(
            model_name='phieunhapsach',
            name='NguoiNhap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phieunhapsach_created', to=settings.AUTH_USER_MODEL, verbose_name='Người nhập'),
        ),
        migrations.AddField(
            model_name='phieuthutien',
            name='NguoiThu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phieuthutien_created', to=settings.AUTH_USER_MODEL, verbose_name='Người thu'),
        ),
    ]
