# Generated by Django 5.2 on 2025-05-07 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_hoadon_nguoilaphd_phieunhapsach_nguoinhap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadon',
            name='NguoiLapHD',
        ),
        migrations.RemoveField(
            model_name='phieuthutien',
            name='NguoiThu',
        ),
        migrations.AlterField(
            model_name='phieunhapsach',
            name='NguoiNhap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phieunhapsach_created', to=settings.AUTH_USER_MODEL, verbose_name='Người nhập'),
        ),
    ]
