# Generated by Django 5.2 on 2025-05-07 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_remove_hoadon_nguoilaphd_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='NguoiLapHD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hoadon_created', to=settings.AUTH_USER_MODEL, verbose_name='Người lập HĐ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phieuthutien',
            name='NguoiThu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='phieuthutien_created', to=settings.AUTH_USER_MODEL, verbose_name='Người thu'),
            preserve_default=False,
        ),
    ]
