# Generated by Django 5.2 on 2025-05-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_hoadon_nguoilaphd_phieuthutien_nguoithu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ct_bcton',
            name='TonCuoi',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='ct_hoadon',
            name='ThanhTien',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
    ]
